title: Bad Redactions
description: >-
    This Add-on allows you to select multiple documents, uses x-ray library to identify bad redactions,
    creates annotations where bad redactions exist, and exports document_ids, page numbers, bounding boxes and the text in a csv file.
    By checking the box, this will redact bad redactions and delete any existing bad redaction annotations.


    **Warning**: Once you check this box and run this Add-On, you cannot undo redactions.
    [Learn more about X-Ray Library](https://free.law/projects/x-ray).
instructions: ''
type: object
documents:
  - selected
  - query
properties:
    fix:
      title: Redact bad redactions found?
      type: boolean
categories:
  - extraction
