# The title is the title of your Add-On
title: Bad Redactions
# The description will be shown above the form when activating the Add-On
description: This is an add-on that identifies bad redactions and returns the page numbers, bounding boxes and the text.
# Type should always be object
type: object
# How does this add-on accept documents
# If more than one type is specified, the user will be prompted to choose one
documents:
  # By the currently selected documents
  - selected
# Properties are the fields for your form
properties: {}
